import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from "@/app/components/Footer";
import Header2 from "@/app/components/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`inter.className flex min-h-screen flex-col`}>
      <Header2/>
      <main className="flex-1">
        {children}
      </main>
      <Footer/>
      </body>
    </html>
  )
}
